import { useNavigate, useLocation } from "react-router-dom";
import {
  Lock,
  Ban,
  SearchX,
  TriangleAlert,
  ArrowLeft,
  Home,
  RefreshCw,
  KeyRound,
} from "lucide-react";

/* ─────────────────────────────────────────────────────────────────
   Error-code configuration — every color below is a Tailwind class
   name (from the shared palette / theme.css tokens), never a raw hex
   or an inline style. -webkit-text-stroke has no Tailwind utility, so
   it's expressed as a Tailwind arbitrary-property class instead of a
   style attribute — still a class, still generated by Tailwind.
───────────────────────────────────────────────────────────────── */
const ERROR_CONFIG = {
  401: {
    code: "401",
    strokeClass: "[-webkit-text-stroke:1.5px_var(--color-amber-500)]",
    solidBg: "bg-amber-500 hover:bg-amber-600",
    solidFg: "text-white",
    blobBg: "bg-amber-500",
    badgeBg: "bg-amber-500/10",
    badgeBorder: "border-amber-500/30",
    badgeText: "text-amber-500",
    codePillBg: "bg-amber-500/10",
    codePillText: "text-amber-500",
    heading: "Authentication required",
    description:
      "You need to be signed in to access this page. Please log in with your credentials.",
    actions: ["login", "back"],
    Icon: Lock,
  },
  403: {
    code: "403",
    strokeClass: "[-webkit-text-stroke:1.5px_var(--color-red-500)]",
    solidBg: "bg-red-500 hover:bg-red-600",
    solidFg: "text-white",
    blobBg: "bg-red-500",
    badgeBg: "bg-red-500/10",
    badgeBorder: "border-red-500/30",
    badgeText: "text-red-500",
    codePillBg: "bg-red-500/10",
    codePillText: "text-red-500",
    heading: "Access forbidden",
    description:
      "You don't have permission to view this page. Contact your administrator if you believe this is a mistake.",
    actions: ["dashboard", "back"],
    Icon: Ban,
  },
  404: {
    code: "404",
    strokeClass: "[-webkit-text-stroke:1.5px_var(--color-accent)]",
    solidBg: "bg-accent hover:bg-accent/90",
    solidFg: "text-accent-foreground",
    blobBg: "bg-accent",
    badgeBg: "bg-accent/10",
    badgeBorder: "border-accent/30",
    badgeText: "text-accent",
    codePillBg: "bg-accent/10",
    codePillText: "text-accent",
    heading: "Page not found",
    description: "The page you're looking for doesn't exist or has been moved.",
    actions: ["dashboard", "back"],
    Icon: SearchX,
  },
  500: {
    code: "500",
    strokeClass: "[-webkit-text-stroke:1.5px_var(--color-violet-500)]",
    solidBg: "bg-violet-500 hover:bg-violet-600",
    solidFg: "text-white",
    blobBg: "bg-violet-500",
    badgeBg: "bg-violet-500/10",
    badgeBorder: "border-violet-500/30",
    badgeText: "text-violet-500",
    codePillBg: "bg-violet-500/10",
    codePillText: "text-violet-500",
    heading: "Internal server error",
    description:
      "Something went wrong on our end. Our team has been notified. Please try again in a moment.",
    actions: ["retry", "dashboard", "back"],
    Icon: TriangleAlert,
  },
};

/* ─────────────────────────────────────────────────────────────────
   Main component
   Props:
     status   401 | 403 | 404 | 500   (default 404)
     embedded render inside AdminLayout content area
───────────────────────────────────────────────────────────────── */
export default function ErrorPage({ status = 404, embedded = false }) {
  const navigate = useNavigate();
  const location = useLocation();
  const cfg = ERROR_CONFIG[status] ?? ERROR_CONFIG[404];

  const renderActions = () => {
    const btns = [];

    if (cfg.actions.includes("retry")) {
      btns.push(
        <button
          key="retry"
          type="button"
          onClick={() => window.location.reload()}
          className={`flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold text-white cursor-pointer transition-all duration-150 hover:brightness-110 shadow-md ${cfg.badgeBg} ${cfg.badgeText} border ${cfg.badgeBorder}`}
        >
          <RefreshCw size={15} /> Try again
        </button>,
      );
    }
    if (cfg.actions.includes("login")) {
      btns.push(
        <button
          key="login"
          type="button"
          onClick={() => navigate("/admin/login")}
          className={`flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold cursor-pointer transition-all duration-150 shadow-md ${cfg.solidBg} ${cfg.solidFg}`}
        >
          <KeyRound size={15} /> Sign in
        </button>,
      );
    }
    if (cfg.actions.includes("dashboard")) {
      btns.push(
        <button
          key="dashboard"
          type="button"
          onClick={() => navigate("/admin/dashboard")}
          className={`flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold cursor-pointer transition-all duration-150 shadow-md ${cfg.solidBg} ${cfg.solidFg}`}
        >
          <Home size={15} /> Go to Dashboard
        </button>,
      );
    }
    if (cfg.actions.includes("back")) {
      btns.push(
        <button
          key="back"
          type="button"
          onClick={() => navigate(-1)}
          className="flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl border border-border bg-card text-muted-foreground text-sm font-medium cursor-pointer hover:bg-accent/10 hover:text-foreground transition-colors shadow-sm"
        >
          <ArrowLeft size={15} /> Go back
        </button>,
      );
    }
    return btns;
  };

  const inner = (
    <div
      className={`flex flex-col items-center text-center relative z-10 ${embedded ? "w-full py-14 px-6" : "max-w-md w-full"}`}
    >
      {/* Big error code — text-stroke-only digits, no fill */}
      <div className="relative select-none mb-3">
        <span
          className={`text-transparent text-[clamp(5.5rem,20vw,10rem)] font-black leading-none tracking-tight ${cfg.strokeClass}`}
        >
          {cfg.code}
        </span>
        <span
          aria-hidden="true"
          className={`absolute inset-0 text-[clamp(5.5rem,20vw,10rem)] font-black leading-none tracking-tight blur-[6px] opacity-20 ${cfg.badgeText}`}
        >
          {cfg.code}
        </span>
      </div>

      {/* Icon badge */}
      <div
        className={`mb-5 w-14 h-14 rounded-2xl flex items-center justify-center border ${cfg.badgeBg} ${cfg.badgeBorder} ${cfg.badgeText}`}
      >
        <cfg.Icon size={28} strokeWidth={1.8} />
      </div>

      <h1 className="text-2xl sm:text-3xl font-bold text-foreground mb-3">{cfg.heading}</h1>
      <p className="text-muted-foreground text-sm sm:text-[15px] leading-relaxed mb-3 max-w-sm">
        {cfg.description}
      </p>

      <p className="mb-8 text-xs text-muted-foreground opacity-55">
        Path:{" "}
        <code
          className={`px-2 py-0.5 rounded text-[11.5px] font-mono ${cfg.codePillBg} ${cfg.codePillText}`}
        >
          {location.pathname}
        </code>
      </p>

      <div className="flex flex-col sm:flex-row flex-wrap gap-3 w-full sm:w-auto justify-center">
        {renderActions()}
      </div>
    </div>
  );

  if (embedded) {
    return (
      <div className="flex flex-col items-center justify-center min-h-115 relative overflow-hidden rounded-2xl">
        <div
          aria-hidden="true"
          className={`pointer-events-none absolute top-0 left-1/2 -translate-x-1/2 w-125 h-80 opacity-[0.06] rounded-full blur-3xl ${cfg.blobBg}`}
        />
        {inner}
      </div>
    );
  }

  return (
    <div className="min-h-svh flex flex-col items-center justify-center p-6 bg-background overflow-hidden relative">
      <div
        aria-hidden="true"
        className={`pointer-events-none absolute -top-32 -left-32 w-125 h-125 rounded-full opacity-[0.07] blur-3xl ${cfg.blobBg}`}
      />
      <div
        aria-hidden="true"
        className={`pointer-events-none absolute -bottom-32 -right-32 w-110 h-110 rounded-full opacity-[0.06] blur-3xl ${cfg.blobBg}`}
      />
      {inner}
      <p className="absolute bottom-6 text-[11.5px] text-muted-foreground opacity-45 select-none">
        TheStrengthWay Admin · Error {cfg.code}
      </p>
    </div>
  );
}

export const UnauthorizedPage = (props) => <ErrorPage status={401} {...props} />;
export const ForbiddenPage = (props) => <ErrorPage status={403} {...props} />;
export const AdminNotFoundPage = (props) => <ErrorPage status={404} {...props} />;
export const ServerErrorPage = (props) => <ErrorPage status={500} {...props} />;
