// Pre-seeded rich accreditation documents based on trainer certification names
export const PRESET_ACCREDITATION_METADATA = {
  "CrossFit Level 2 Coach": {
    issuer: "CrossFit LLC Training Board",
    issueDate: "2022-04-18",
    expiryDate: "2027-04-18",
    fileName: "CrossFit_L2_Certificate.pdf",
    fileSize: "2.4 MB",
    credentialId: "CF-884920-L2",
  },
  "CSCS Specialist": {
    issuer: "National Strength & Conditioning Association (NSCA)",
    issueDate: "2021-08-12",
    expiryDate: "Lifetime / Validated",
    fileName: "CSCS_Accreditation_Doc.pdf",
    fileSize: "1.9 MB",
    credentialId: "NSCA-77491-CSCS",
  },
  "ACE Certified Personal Trainer": {
    issuer: "American Council on Exercise (ACE)",
    issueDate: "2020-11-05",
    expiryDate: "2026-11-05",
    fileName: "ACE_Certified_PT.pdf",
    fileSize: "3.1 MB",
    credentialId: "ACE-99410-CPT",
  },
  "Functional Movement Screen (FMS)": {
    issuer: "FMS Functional Movement Systems",
    issueDate: "2023-02-20",
    expiryDate: "2027-02-20",
    fileName: "FMS_Level1_Verification.pdf",
    fileSize: "1.4 MB",
    credentialId: "FMS-55210-PRO",
  },
  "CSCS (Certified Strength & Conditioning Specialist)": {
    issuer: "National Strength & Conditioning Association (NSCA)",
    issueDate: "2020-06-14",
    expiryDate: "Lifetime / Validated",
    fileName: "CSCS_Master_Accreditation.pdf",
    fileSize: "2.8 MB",
    credentialId: "NSCA-90234-CSCS",
  },
  "USA Weightlifting (USAW-1)": {
    issuer: "USA Weightlifting Coaching Board",
    issueDate: "2021-09-30",
    expiryDate: "2026-09-30",
    fileName: "USAW_Olympic_Lifting_Cert.pdf",
    fileSize: "1.7 MB",
    credentialId: "USAW-44321-L1",
  },
  "ISSA Elite Master Trainer": {
    issuer: "International Sports Sciences Association",
    issueDate: "2019-12-10",
    expiryDate: "Lifetime / Validated",
    fileName: "ISSA_Master_Trainer.pdf",
    fileSize: "3.2 MB",
    credentialId: "ISSA-88390-EMT",
  },
  "Precision Nutrition Level 1": {
    issuer: "Precision Nutrition Academy",
    issueDate: "2022-07-22",
    expiryDate: "Lifetime / Validated",
    fileName: "Precision_Nutrition_L1.pdf",
    fileSize: "2.1 MB",
    credentialId: "PN1-66420-EXP",
  },
  "NASM Corrective Exercise Specialist (CES)": {
    issuer: "National Academy of Sports Medicine (NASM)",
    issueDate: "2021-03-15",
    expiryDate: "2027-03-15",
    fileName: "NASM_CES_Accreditation.pdf",
    fileSize: "2.6 MB",
    credentialId: "NASM-77120-CES",
  },
  "EXOS Performance Specialist": {
    issuer: "EXOS Athletic Performance Academy",
    issueDate: "2022-10-08",
    expiryDate: "2026-10-08",
    fileName: "EXOS_Performance_Cert.pdf",
    fileSize: "1.8 MB",
    credentialId: "EXOS-33190-XPS",
  },
  "Sports Physical Therapy Associate": {
    issuer: "APTA Sports Physical Therapy Section",
    issueDate: "2020-05-19",
    expiryDate: "Lifetime / Validated",
    fileName: "Sports_PT_Associate_Doc.pdf",
    fileSize: "3.4 MB",
    credentialId: "APTA-55910-SPT",
  },
  "TRX Suspension Master Coach": {
    issuer: "TRX Training International",
    issueDate: "2023-01-14",
    expiryDate: "2027-01-14",
    fileName: "TRX_Suspension_Mastery.pdf",
    fileSize: "1.2 MB",
    credentialId: "TRX-11940-MST",
  },
};
